### ISSUE TITLE
EPIC: As a project manager, I would like to have under control the entering and exiting data flows from ODH Mobility

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-core#136]
Proposal of tasks:
- [x] @bertolla will atart to analyze the issue and maybe organize a meeting with the developers and Roberto to share the results
- [ ] Extend the A22 view of Graphana also to other Data Collectors, other KPI / plots should be investigated
- [ ] Generate a daily mail in which information currently stored in https://github.com/noi-techpark/issues/blob/master/missingData.md are transmitted. Data Collectors that are not transmitting since 24 hours should be explicitly highlighted
- [ ] Evaluate to apply all this also to our APIv2, so to check if there are mismatches between entering data and data made available to 3rd parties

**Comment by rcavaliere** [comment]
@bertolla I have seen your concept draft. For me it is OK. The only thing, I would generate a daily (not weekly) summary of the issues that have observed.

**Comment by dulvui** [comment]
deprecated by new infrastrucutre
