### ISSUE TITLE
EPIC: as an Open Data Hub manager I want the entire AWS server infrastructure migrated to the new Root Account.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/bdp-core#199]
- [x] Claranet provides the list of information needed to start the migration of the root account
- [x] NOI will provide the information to Claranet
- [x] Claranet will take over the root account.

**Comment by rcavaliere** [comment]
All team is requested to test if everything works, then we will close the user story.
