### ISSUE TITLE
EPIC: As a project manager I want to enhance the ODH Mobility core so to efficiently integrate traffic events

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/bdp-core#205]
Deadline: 28 February 2022

@bertolla (with support by @Piiit for the DB modeling)
- [x] Design DB model
- [x] Create DB model
- [x] Writer API enhancement

@Piiit 

- [x] Fix the writer to use Postgres rangetypes and not bytea for intervals
- [x] include a provenance into events
- [x] Modernize the writer code to use spring boot and .env files
  - [x] writer
  - [x] dto
  - [x] dal (merge into writer)
  - [x] dc-interface
  - [x] remove: ws-interface
  - [x] remove: tools
  - [x] remove: api v1
- [x] Fix the log4j shell vulnerability
- [x] Decide if we want to use timezones @rcavaliere 
   > We use timezones, but we should do that in all time related fields... this is another user story #213 for the future therefore
- [x] Use half-open intervals for events
- [x] Introduce flyway and schema migrations
- [x] improve local development with docker, that is, start a local postgres and fill it with the initial schema from the migrations
- [x] fix measurementjsonhistory duplicates and unique constraint
  - [x] clean testing DB
  - [x] clean production DB
- [x] Should we use `category,name` and not only `uuid` as unique compound key
   > We decided to create some new unique constraints for this... the exact design must still be done
- [x] Ninja API enhancement

**Comment by rcavaliere** [comment]
Basic concept of DB structure:

“events”
    • Id
    • categoria
    • sottocategoria
    • created_on
    • descripton
      
      
“events_metadata”
    • id
    • json

“events_interval”
    • id
    • data_inizio
    • data_fine
    • description

“events_geometry”
    • id
    • location (geometry)
    • description

**Comment by bertolla** [comment]
For the location I propose to use geojson in the dto, to have a valid geometry that can accommodate everything

**Comment by rcavaliere** [comment]
@bertolla ok, does this have an impact on the DB table structure above?

**Comment by bertolla** [comment]
I deployed the writer with the changes on the testserver.
The version of the dc-interface to use is 5.3.0-SNAPSHOT.
The new added call is addEvents(List<EventDto>). Maybe Davide could already test it out in the test environment
Maybe

**Comment by Piiit** [comment]
@rcavaliere I move this to TODO, because it is a prerequisite of https://github.com/noi-techpark/bdp-commons/issues/263

**Comment by Piiit** [comment]
@rcavaliere Done, please test... https://mobility.api.opendatahub.testingmachine.eu

The README has some minimal examples too --> https://github.com/noi-techpark/it.bz.opendatahub.api.mobility-ninja#events
