### ISSUE TITLE
EPIC: As a contributor to the BDP, I want to create new data collectors and web services without the need to change the core.

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/bdp-core#28]
- [x] Remove inheritance based station types
- [x] Introduce JSON based meta data to replicate subclasses previously modelled with inheritance
- [x] Create a mechanism to store also historical JSON based meta data #29
- [x] Create new versions of data collectors and web services, that use the new JSON based models
- [x] Create a proper error handling for writer (errors should bubble up to a response, http codes and response always as JSON) #11
- [x] Create a proper error handling for reader (errors should bubble up to a response, http codes and response always as JSON) #46 
- Rewrite all queries to use meta-data instead of old separate detail tables
  - [x] Move CarParkingDynamic handling into the data collector
  - [x] Move CarPooling translations into Station JSON meta data
  - [x] Move TrafficVehicleRecord handling into data collector
    > We remove these for the moment from DAL and open a separate issues for a later migration #48
- [x] Create a new schema dump and modification script
- [x] Update documentation #84 
- [x] Update contributors and license headers
- [x] Write a migration SQL script to update schema and move table data from v1 to v2 #49 
- [x] Test core, data collectors and web services on our testing environment #50 
- [x] Migrate core, data collectors and web services to our production environment #51
- [x] Update all queries inside our tiles server (aka Geoserver) #54
- [x] Merge development into master and release a new version
