### ISSUE TITLE
EPIC: As a consumer of the Open Data Hub Apis i want to have a SSO Solution

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/bdp-core#92]
**TODO (mostly deprecated, since we switched to Keycloak)**
- [x] @alexlanz Fixes the odh-auth pipeline next week
- [x] Enable log output (development mode) on the .net core oauth server
- [x] Implement an authentication mechanism with the general ODH Oauth 2.0 server to fetch protected data
- [x] As a consumer of the ODH Mobility API, I want to get protected information https://github.com/noi-techpark/bdp-core/issues/104
> This works and is on the branch "ninja-oauth", however I cannot deploy it, because the oauth server allows to generate new users and roles without protection
- [ ] As a consumer of the ODH Tourism API, I want to get protected information 
- [ ] Oauth Server: Add authentication for https://admin.auth.testingmachine.eu
- [ ] Oauth Server: Add "aud" lists, that represent the resource server urls (APIs), that are allowed to access 
- [ ] Oauth Server: Add "scopes" for "read" and "write"
- [ ] Oauth Server: Add a registration for "client_id" and "client_secret"

**INFO**
- https://auth.testingmachine.eu
- https://auth.testingmachine.eu/.well-known/openid-configuration
- https://admin.auth.testingmachine.eu/swagger/index.html
- https://jwt.io/
- https://spring.io/guides/tutorials/spring-boot-oauth2/
- https://www.baeldung.com/swagger-2-documentation-for-spring-rest-api

**Comment by Piiit** [comment]
@alexlanz @RudiThoeni Server currently not online, pipeline fix needed.

**Comment by Piiit** [comment]
Rudi fixed it :-)

**Comment by Piiit** [comment]
@rcavaliere @RudiThoeni This works now for the mobility API v2. I dunno exactly what the state is for the tourism API. However, we cannot deply the code yet, because the oauth server itself allows creation of users and roles without authentication. It is a test-installation... hence, it is ok for now. We just need to get those things done... :-)
